blogXpaths = {
	'qgblog.people.com.cn':{
                'lang':'zh',
                'title':['//*[@id="p_title"]'],
                'pdate':['//*[@id="p_publishtime"]'],
                'showcontent':['//*[@id="p_content"]'],
        },
        'blog.ifeng.com':{
                'lang':'zh',
                'title':['//*[@class="blog_main_left_content"]/h3'],
                'pdate':['//*[@class="blog_main_time"]/p'],
                'showcontent':['//*[@id="blog_article_content"]'],
        },
        'blog.sohu.com':{
                'lang':'zh',
                'title':['//*[@class="newBlog-title"]/h2'],
                'pdate':['//*[@class="date"]'],
                'showcontent':['//*[@id="main-content"]'],
        },
        'blog.163.com':{
                'lang':'zh',
                'title':['//*[@class="tcnt"]'],
                'pdate':['//*[@class="blogsep"]'],
                'showcontent':['//*[@class="bct fc05 fc11 nbw-blog ztag"]'],
        },
        'blog.tianya.cn':{
                'lang':'zh',
                'title':['//h2/a'],
                'pdate':['//*[@class="pos-right gray6"]'],
                'showcontent':['//*[@class="article-summary articletext"]'],
        },
        'blog.qq.com':{
                'lang':'zh',
                'title':['//*[@id="blogTitle"]'],
                'pdate':['//*[@id="publishDate"]'],
                'showcontent':['//*[@id="bContent"]'],
        },
	'blog.sina.com.cn':{
                'lang':'zh',
                'title':['//*[@id="artibodyTitle"]/h2'],
                'pdate':['//*[@class="time SG_txtc"]'],
                'showcontent':['//*[@id="sina_keyword_ad_area2"]','//*[@class="articalContent   "]'],
        },
	'blogchina.com':{
                'lang':'zh',
                'title':['//*[@class="title"]/div'],
                'pdate':['//*[@class="time"]'],
                'showcontent':['//*[@class="article"]'],
        },
}

newsXpaths = {
	'weixin.qq.com':{
                'lang':'zh',
                'title':['//*[@id="activity-name"]'],
                'pdate':['//*[@id="post-date"]'],
                'showcontent':['//*[@id="js_content"]'],
        },
	'qq.com':{
                'lang':'zh',
                'title':['//*[@class="hd"]/h1','//h1'],
                'pdate':['//*[@class="a_time"]','//*[starts-with(@class,"pubTime")]'],
                'showcontent':['//*[@id="Cnt-Main-Article-QQ"]'],
        },
        '163.com':{
                'lang':'zh',
                'title':['//*[@id="epContentLeft"]/h1'],
                'pdate':['//*[@class="post_time_source"]'],
                'showcontent':['//*[@id="endText"]//p'],
        },
        'ifeng.com':{
                'lang':'zh',
                'title':['//*[@id="artical_topic"]','//*[@class="title"]/h2'],
                'pdate':['//*[@itemprop="datePublished"]','//*[@class="marb-5"]/span'],
                'showcontent':['//*[@id="main_content"]','//*[@class="article"]','//*[@class="arl-c-txt"]'],
        },
        'sina.com.cn':{
                'lang':'zh',
                'title':['//*[@id="artibodyTitle"]/h1'],
                'pdate':['//*[@class="time-source"]'],
                'showcontent':['//*[@id="artibody"]'],
        },
	'home.news.cn':{
                'lang':'zh',
                'title':['//*[@id="doc_content"]/h1'],
                'pdate':['//*[@id="ct"]/table[1]/tbody/tr[5]/td/table/tbody/tr/td[5]'],
                'showcontent':['//*[@id="articleContent"]'],
        },
        'jiemian.com':{
                'lang':'zh',
                'title':['//*[@class="article-header"]'],
                'pdate':['//*[@class="date"]'],
                'showcontent':['//*[@class="article-content"]'],
        },      
        'thepaper.cn':{
                'lang':'zh',
                'title':['//*[@class="news_title"]'],
                'pdate':['//*[@class="news_about"]'],
                'showcontent':['//*[@class="news_txt"]'],
        },
        'fang.com':{
                'lang':'zh',
                'title':['//*[@class="at-tit"]','//*[@class="news-title"]'],
                'pdate':['//*[@class="fb-time"]','//*[@class="assis-title"]','//*[@class="comment clearfix"]'],
                'showcontent':['//*[@class="whole"]','//*[@class="news-text"]','//*[@class="news-detail-content shadow clears"]'],
        },
	'xinhuanet.com':{
                'lang':'zh',
                'title':['//*[@id="ArticleTit"]','//*[@class="h-title"]','//*[@id="title"]','//*[@id="news_title"]','//*[@class="black18"]'],
                'pdate':['//*[@id="Articlely"]','//*[@class="h-time"]','//*[@id="pubtime"]','//*[@class="info"]','//*[@class="head_detail_t"]','//*[@class="black12"]'],
                'showcontent':['//*[@class="content"]','//*[@id="p-detail"]','//*[@id="content"]','//*[@class="article"]','//*[@id="news_content"]','//*[@id="Content"]','//*[@id="newsdetail-content-text"]'],
        },
	'focus.cn':{
                'lang':'zh',
                'title':['//*[@class="main-content"]/h1','//*[@class="new-detail-left"]/h1','//h1'],
                'pdate':['//*[@class="info-source"]'],
                'showcontent':['//*[@id="newscontent"]','//*[@class="info-content"]',],
        },
	'leju.cn':{
                'lang':'zh',
                'title':['//h1[@class="title"]','//h1'],
                'pdate':['//*[@class="titlesub clearfix"]','//strong'],
                'showcontent':['//*[@class="article-body"]'],
        },
	'people.com.cn':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@class="fl"]'],
                'showcontent':['//*[@id="rwb_zw"]'],
        },
	'hexun.com':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@class="pr20"]'],
                'showcontent':['//*[@class="art_contextBox"]'],
        },
	'chinanews.com':{
                'lang':'zh',
                'title':['//*[@id="cont_1_1_2"]/h1'],
                'pdate':['//*[@class="left-t"]'],
                'showcontent':['//*[@class="left_zw"]'],
        },
	'chinadaily.com.cn':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@id="pubtime"]'],
                'showcontent':['//*[@id="Content"]'],
        },
	'house.china.com.cn':{
                'lang':'zh',
                'title':['//*[@class="xwbt"]/h1'],
                'pdate':['//*[@id="pubtime_baidu"]'],
                'showcontent':['//*[@class="xwzw"]'],
        },
	'nbd.com.cn':{
                'lang':'zh',
                'title':['//h1','/html/head/title'],
                'pdate':['//*[@class="time"]','//*[@class="article-meta"]'],
                'showcontent':['//*[@class="g-articl-text"]','//*[@class="n_articleContainer"]'],
        },
	'yicai.com':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@class="f-ff1 f-fwn f-fs14"]'],
                'showcontent':['//*[@class="m-text"]'],
        },
	'eeo.com.cn':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@class="xd-b-b"]/p'],
                'showcontent':['//*[@class="xd-nr"]'],
        },
	'jjckb.cn':{
                'lang':'zh',
                'title':['//*[starts-with(@class,"top_tit")'],
                'pdate':['//*[@class="sj_scro"]'],
                'showcontent':['//*[@id="content"]'],
        },
	'21cn.com':{
                'lang':'zh',
                'title':['//h1'],
                'pdate':['//*[@class="pubTime"]'],
                'showcontent':['//*[@id="article_text"]'],
        },
	'tieba.baidu.com':{
                'lang':'zh',
                'title':['//*[@id="j_core_title_wrap"]/h3'],
                'pdate':['//*[@class="tail-info"]'],
                'showcontent':['//*[starts-with(@id,"post_content")]'],
        },
	'guojiribao.com':{
                'lang':'zh',
                'title':['//*[@id="content"]/h1','//h1'],
                'pdate':['//*[@class="d_d"]'],
                'showcontent':['//*[@id="content_div"]'],
        },
	'scmp.org.cn':{
                'lang':'zh',
                'title':['//h1[@class="spacing"]','//h1'],
                'pdate':['//*[@class="updataTime "]'],
                'showcontent':['//*[@id="wrapper"]/table[2]/tbody/tr/td[1]/table[2]/tbody/tr/td/table[2]/tbody/tr[2]','//*[@align="left"]//p'],
        },
	'wenweipo.com':{
                'lang':'zh',
                'title':['//*[@class="title"]','//h1'],
                'pdate':['//*[@class="date"]'],
                'showcontent':['//*[@id="main-content"]'],
        },
        'enanyang.my':{
                'lang':'zh',
                'title':['//*[@class="entry-title"]','//h2'],
                'pdate':['//*[@class="time-meta"]/@datetime','//*[@class="time-meta"]'],
                'showcontent':['//*[@class="entry-content"]//p'],
        },
        'zaobao.com':{
                'lang':'zh',
                'title':['//meta[@itemprop="name"]/@content','//*[@id="zbListingPageTitle"]','//h1'],
                'pdate':['//meta[@property="article:published_time"]/@content','//*[@class="datestamp"]/text()'],
                'showcontent':['//*[@id="article-body"]','//*[@id="zbArticlePageContent"]','//*[@id="FineDining"]','//*[@class="the_content_wrapper"]'],
        },
        'hket.com':{
                'lang':'zh',
                'title':['//*[@id="eti-article-headline"]/h1','//h1'],
                'pdate':['//*[@id="eti-article-functions"]/div[1]','//*[@class="datetime"]','//*[@class="article-details-fn-cotainer_date"]','//*[@style="float:left; font-size:15px"]'],
                'showcontent':['//*[@id="eti-article-content"]','//*[@class="article-detail-content-container"]'],
        },
        'takungpao.com':{
                'lang':'zh',
                'title':['//*[@class="tpk_con_tle"]/h1','//h1','//*[@id="title_tex"]','//h3'],
                'pdate':['//*[@class="article_info_l fl_dib"]','//*[@id="time_tex"]','//*[@class="con_left"]'],
                'showcontent':['//*[@class="tpk_text clearfix"]','//*[contains(@class, "tpk_text")]','//*[@id="details-con"]','//*[@id="sheets"]'],
        },
	'cnn.com':{
                'lang':'en',
                'title':['//h1[@class="pg-headline"]','//*[@class="article-title speakable"]','//h1','//h2'],
                'pdate':['//*[@class="update-time"]','//*[contains(@class, "date")]','//*[contains(@class, "Date")]'],
                'showcontent':['//*[@class="l-container"]','//*[@id="storytext"]','//*[contains(@class, "content")]','//*[contains(@class, "Content")]'],
        },
	'ap.org':{
                'lang':'en',
                'title':['//*[@id="page-title"]','//*[@class="headline entry-title"]','//h1'],
                'pdate':['//*[@itemprop="datePublished"]/@datetime','//*[@class="timestamp updated"]/@title','//*[@class="updated"]/@title'],
                'showcontent':['//*[@itemprop="mainEntityOfPage"]','//*[@class="body"]','//*[@class="content clearfix article-body"]'],
        },
	'apnews.com':{
                'lang':'en',
                'title':['//*[@class="topTitle"]','//h1'],
                'pdate':['//*[@class="updatedString"]'],
                'showcontent':['//*[@class="articleBody"]'],
        },
	'forbes.com':{
                'lang':'en',
                'title':['//*[@itemprop="headline"]','//h1'],
                'pdate':['//*[@itemprop="datePublished"]/@datetime','//meta[@name="pub_date"]/@content','//meta[@name="date"]/@content','//*[@class="date-header"]'],
                'showcontent':['//*[@itemprop="articleBody"]','//*[@class="article-body-content"]','//*[@class="body"]','//*[@id="fab"]'],
        },
	'yahoo.com':{
                'lang':'en',
                'title':['//*[@itemprop="headline"]','//h1'],
                'pdate':['//*[@itemprop="datePublished"]/@datetime'],
                'showcontent':['//*[@itemprop="articleBody"]'],
        },
	'abcnews.go.com':{
                'lang':'en',
                'title':['//*[@id="_stage"]/h1','//*[@itemprop="headline"]','//meta[@property="og:title"]/@content','//h1'],
                'pdate':['//meta[@name="Date"]/@content','//meta[@itemprop="datepublished"]/@content','//meta[@itemprop="uploadDate"]/@content'],
                'showcontent':['//*[@class="article-copy"]','//*[@itemprop="articleBody"]','//*[@id="storyText"]'],
        },
	'bbc.com':{
                'lang':'en',
                'title':['//*[@class="story-body"]/h1','//h1'],
                'pdate':['//*[@class="mini-info-list__item"]/div/@data-seconds','//meta[@property="rnews:datePublished"]/@content','//*[@class="publication-date index-body"]'],
                'showcontent':['//*[@property="articleBody"]','//*[@class="body-content"]','//*[@id="story-body"]'],
        },
	'straitstimes.com':{
                'lang':'en',
                'title':['//*[@itemprop="headline"]','//*[@class="headline node-title"]','//h1'],
                'pdate':['//*[@itemprop="datePublished"]/@data-timestamp','//meta[@property="article:published_time"]/@content'],
                'showcontent':['//*[@itemprop="articleBody"]','//*[@class="the_content_wrapper"]'],
        },
	'nst.com.my':{
                'lang':'en',
                'title':['//*[@class="ph-wrapper"]'],
                'pdate':['//*[@class="post-date"]'],
                'showcontent':['//*[@class="field-item even"]','//*[@class="field-items"]'],
        },
	'rtm.gov.my':{
                'lang':'en',
                'title':['//h1[@itemprop="name"]','//h1'],
                'pdate':['//*[@itemprop="dateCreated"]/@datetime','//*[@itemprop="dateCreated"]'],
                'showcontent':['//*[@itemprop="articleBody"]'],
        },
	'thestar.com.my':{
                'lang':'en',
                'title':['//*[@class="headline"]','//h2'],
                'pdate':['//*[@id="slcontent3_6_sleft_0_pDate"]','//*[@class="date"]'],
                'showcontent':['//*[@id="slcontent3_6_sleft_0_storyDiv"]','//*[@class="story"]'],
        },
	'utusan.com.my':{
                'lang':'en',
                'title':['//*[@name="title"]/@content','//h1'],
                'pdate':['//*[@itemprop="datePublished"]'],
                'showcontent':['//*[@id="articleBody"]'],
        },
	
	'ausdaily.net.au':{
                'lang':'en',
                'title':['//*[@class="headline"]','//h3'],
                'pdate':['//*[@class="byline"]'],
                'showcontent':['//article//p'],
        },
	'theaustralian.com.au':{
                'lang':'en',
                'title':['//*[@id="story-headline"]','//h1'],
                'pdate':['//*[@itemprop="datePublished"]/@content','//time'],
                'showcontent':['//*[@id="story"]//p'],
        },
}

xpaths = {

        'www.bjgtj.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="container"]/div[2]/div/div[3]/div[3]/div[2]/div[2]','//*[@id="container"]/div[2]/div/div[3]/div[3]/div/div[2]/div[2]'],
                'pdate':['//*[@id="container"]/div[2]/div/div[3]/div[3]/div[2]/div[3]','//*[@id="container"]/div[2]/div/div[3]/div[3]/div/div[2]/div[3]        '],
                'showcontent':['//div[@id="zoom"]'],
        },

        'www.bjghw.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="main_article_title"]','/html/body/table[4]/tr[2]/td/table/tr[2]/td/strong','/html/body/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr[2]/td/font'],
                'pdate':['//*[@class="article_date"]','/html/body/table[4]/tr[2]/td/table/tr[3]/td/table/tr[2]/td/span[1]','/html/body/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr[3]/td/table/tbody/tr[2]/td/span'],
                'showcontent':['//*[@id="articleContent"]'],
        },
        'www.shgtj.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="ivs_content"]/div//p[@class="p1"]//span','//*[@id="ivs_content"]//p[@class="p1"]//span','//*[@id="ivs_content"]//font/strong','//*[@id="ivs_content"]//strong/font','//*[@id="ivs_content"]//strong'],
                'pdate':['//*[@id="ivs_content"]/div[1]/p[2]/font'],
                'showcontent':['//*[@id="ivs_content"]'],
        },
        'www.shjjw.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="ivs_title"]'],
                'pdate':['//*[@id="main"]/div[2]/div/div[2]/span'],
                'showcontent':['//*[@id="ivs_content"]'],
        },
        'www.tjcac.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="show_bt"]','//*[@id="container"]/div[5]/div[2]/div[1]','//*[@id="container"]//div[@class="TRS_PreAppend"]/p[1]/span','//div[@class="new_show"]/h1','//h1'],
                'pdate':['//*[@id="container"]/div[4]/div[2]/div[3]/div[1]/span[3]'],
                'showcontent':['//*[@id="TRS_Editor"]','//*[@class="TRS_Editor"]','//*[@class="content"]'],
        },
        'www.tjsqgt.gov.cn': {
                'lang':'zh',
                'title':['//*[starts-with(@id, "WebPartWPQ")]/table/tr[3]/td[2]/table/tr[1]','//*[@id="ctl00_PlaceHolderMain_Content__ControlWrapper_RichHtmlField"]/p[1]','//*[@id="WebPartWPQ7"]/table/tbody/tr[1]/td/p[1]/strong/span/font'],
                'pdate':['//*[@id="WebPartWPQ6"]/table/tr[3]/td[2]/table/tr[2]/td[2]'],
                'showcontent':['//*[@id="WebPartWPQ6"]/table/tr[3]/td[2]/table/tr[3]/td[2]/div'],
        },
        'www.cqgtfw.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[3]/div[2]/div[1]/h1'],
                'pdate':['/html/body/div[3]/div[2]/div[1]/h2'],
                'showcontent':['/html/body/div[3]/div[2]/div[1]'],
        },
        'www.ihm.gov.mo': {
                'lang':'zh',
                'title':['//*[@id="content"]/div[3]/div[2]'],
                'pdate':['//*[@id="content"]/div[3]/div[3]'],
                'showcontent':['//*[@id="content"]/div[4]'],
        },
        'www.ahgtt.gov.cn': {
                'lang':'zh',
                'title':['/html/body/table[3]/tr/td/table[2]/tr[2]/td/table[1]/tr[1]/td/h1','//*[@id="containerk"]/table[4]/tr/td/table/tr/td[1]/table[2]/tr[1]/td/table/tr/td/table[1]/tr[2]/td/div','//*[@class="ftitle"]'],
                'pdate':['/html/body/table[3]/tr/td/table[1]/tr[2]/td/table/tr[2]/td[2]'],
                'showcontent':['/html/body/table[3]/tr/td/table[2]/tr[2]/td/table[1]/tr[3]/td','//*[@id="zoom"]','//*[@class="footc"]'],
        },
        'www.fjgtzy.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="middle"]/div/div[2]/h1','//div[@class="content1_2"]','//*[@class="main-mid"]'],
                'pdate':['//*[@id="middle"]/div/div[2]/div/span[1]'],
                'showcontent':['//*[@id="Zoom"]'],
        },
        'www.gdlr.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="newsmall"]/div/h1[2]'],
                'pdate':['//div[@class="times"]'],
                'showcontent':['//*[@id="textbody"]'],
        },
        'www.gxdlr.gov.cn': {
                'lang':'zh',
                'title':['//div[@class="title"]','//*[@id="ctl00_ContentPlaceHolder1_NewsTitleLabel"]','//*[@id="ctl00_ContentPlaceHolder1_Table1"]/tr[1]/td/span','//*[@id="ctl00_ContentPlaceHolder1_DetailForm"]/tr/td/div/h2'],
                'pdate':['//div[@class="info"]','//*[@id="aspnetForm"]/table/tr[2]/td/div[2]/table/tbody/tr[2]/td[1]','//*[@id="ctl00_ContentPlaceHolder1_DetailForm"]/tbody/tr/td/div/h3[1]','//*[@id="ctl00_ContentPlaceHolder1_DetailForm"]/tbody/tr/td/div/table/tbody/tr[2]/td[1]/text()'],
                'showcontent':['//div[@class="content"]','//*[@id="aspnetForm"]/table/tr[2]/td/div[2]/div[5]','//*[@id="aspnetForm"]/table/tbody/tr[2]/td/div/div[4]','//div[@class="content"]'],
        },
        'www.gzcxfgj-gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[5]/div[2]/div[2]/div[1]/h2'],
                'pdate':['/html/body/div[5]/div[2]/div[2]/div[2]/text()[1]'],
                'showcontent':['/html/body/div[5]/div[2]/div[2]//p'],
        },
        'www.lr.hainan.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="body"]/div[2]/div[3]/div/table[1]/tbody/tr[1]/td/table/tbody/tr[1]/td','//*[@id="body"]/div[2]/div[3]/div/form/div/h1'],
                'pdate':['//*[@id="body"]/div[2]/div[3]/div/table[1]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td[6]','//*[@id="body"]/div[2]/div[3]/div/form/div/div[1]/text()[1]'],
                'showcontent':['//*[starts-with(@id,"vsb_content")]'],
        },
        'www.hainan.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[1]/div/div/div/div[2]/div/div[1]/h2','//*[@id="body"]/div[2]/div[3]/div/table[1]/tbody/tr[1]/td/table/tbody/tr[1]/td','//*[@id="body"]/div[2]/div[3]/div/form/div/h1'],
                'pdate':['//*[@id="body"]/div[2]/div[3]/div/table[1]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td[6]','//*[@id="body"]/div[2]/div[3]/div/form/div/div[1]/text()[1]'],
                'showcontent':['//div[@class="conm"]','//*[@id="vsb_content"]'],
        },
        'www.hebfgj.com': {
                'lang':'zh',
                'title':['/html/body/table[2]/tbody/tr/td[1]/table[5]/tbody/tr/td/table[4]/tbody/tr/td','//*[@class="font_title"]','/html/body/table/tbody/tr[3]/td/table[3]/tbody/tr/td[1]/table/tbody/tr[2]/td/table/tbody/tr/td/table[3]/tbody/tr/td','//*[@class="song14pxr"]'],
                'pdate':['/html/body/table[2]/tbody/tr/td[1]/table[5]/tbody/tr/td/table[9]/tbody/tr/td/text()[2]'],
                'showcontent':['//*[@id="zoom"]/div[2]','//*[@//*[@id="zoom"]','//*[@class="union"]'],
        },
        'www.hnjs.gov.cn': {
                'lang':'zh',
                'title':['/html/body/table/tbody/tr[3]/td/div[1]/div[1]/text()','/html/body/table/tbody/tr[3]/td/div/div[1]/table/tbody/tr[1]/td[1]'],
                'pdate':['/html/body/table/tbody/tr[3]/td/div[1]/div[2]','/html/body/table/tbody/tr[3]/td/div/div[1]/table/tbody/tr[3]/td[2]'],
                'showcontent':['/html/body/table/tbody/tr[3]/td/div[2]/div','/html/body/table/tbody/tr[3]/td/div/div[2]'],
        },
        'www.hnfgj-gov.cn': {
                'lang':'zh',
                'title':['//*[@id="container"]/div[6]/div[1]/h1'],
                'pdate':['//*[@id="container"]/div[6]/div[1]/div/span[1]'],
                'showcontent':['//*[@id="news_content"]'],
        },
        'www.hljlr.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[3]/div[1]/div[2]/h1','//*[@class="info-title"]'],
                'pdate':['/html/body/div[3]/div[1]/div[2]/h4/text()[1]'],
                'showcontent':['/html/body/div[3]/div[1]/div[3]/div','//*[@class="TRS_Editor"]','//*[@class="info"]'],
        },
        'www.hblr.gov.cn': {
                'lang':'zh',                
                'title':['/html/body/div[1]/div[3]/div[2]/div[2]/div/h2','//div[@class="cont"]/h3','//*[@class="article"]/h2','//*[@class="zw_bt"]','//*[@class="tc"]','//h2'],
                'pdate':['/html/body/div[1]/div[3]/div[2]/div[2]/div/p/span[1]','//*[@class="info c"]','//*[@class="zw_ly"]'],
                'showcontent':['/html/body/div[1]/div[3]/div[2]/div[2]/div/div[1]','//div[@class="files"]','//*[@class="article-box"]','//*[@class="zw_nr"]','//*[@class="zw_nr_xx"]'],
        },
        'zfbz.changsha.gov.cn': {
                'lang':'zh',                
                'title':['/html/body/div/div/div[2]/div[1]/div/div[2]/div/h1'],
                'pdate':['/html/body/div/div/div[2]/div[1]/div/div[2]/div/div[1]/text()'],
                'showcontent':['//*[@id="article_cont_display"]'],
        },
        'www.hunan.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="sub-article"]/h2'],
                'pdate':['//p[@class="main_conftitp"]/voice'],
                'showcontent':['//*[@id="div_content"]'],
        },
        'www.gtzy.hunan.gov.cn': {
                'lang':'zh',                
                'title':['/html/body/div[3]/table[2]/tbody/tr/td/table/tbody/tr[1]/td','/html/body/div[3]/table[2]/tbody/tr/td/table/tbody/tr[1]/td','/html/body/table[3]/tbody/tr/td/table/tbody/tr[1]/td','/html/body/div/table[2]/tr/td/table/tr[1]/td','/html/body/table[2]/tbody/tr/td/table[1]/tbody/tr[2]/td/table[1]/tbody/tr[2]/td/font','/html/body/div[2]/table[3]/tbody/tr/td[1]/table/tbody/tr/td/table/tbody/tr[2]/td','//div[@class="pagetitel"]'],
                'pdate':['/html/body/div[3]/table[2]/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]','/html/body/div[3]/table[2]/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td[2]'],
                'showcontent':['//*[@class="TRS_Editor"]'],
        },
        'www.hndk.hunan.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="main_content"]/h2'],
                'pdate':['//p[@class="main_conftitp"]/voice'],
                'showcontent':['//*[@class="TRS_Editor"]'],
        },
        'dlr.jl.gov.cn': {
                'lang':'zh',                
                'title':['//*[@class="zybiaotiac"]'],
                'pdate':['//*[@id="container"]/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/table/tbody/tr[3]/td/table/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/table[2]/tbody/tr/td/table/tbody/tr/td[2]'],
                'showcontent':['//*[@id="zoom"]/div','//*[@id="container"]/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/table/tbody/tr[3]/td/table/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/table[4]'],
        },
        'www.jl.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[3]/div[4]/div/div/h2','//*[@style="font-size: 16pt"]','//strong', '//*[@class="red_title"]' ,'//*[@class="detail"]', '//*[@class="news_tit_ly"]'],
                'pdate':['//*[@class="c_xx"]', '/html/body/table[6]/tbody/tr/td/table[3]/tbody/tr/td[1]' ],
                'showcontent':['//*[@id="zoom"]/div','//*[@class="TRS_Editor"]','//*[@id="container"]/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[1]/table/tbody/tr[3]/td/table/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/table[4]'],
        },
        'www.jsmlr.gov.cn': {
                'lang':'zh',                
                'title':['/html/body/table/tr/td/table[2]/tr[1]/td/table[1]/tbody/tr[1]/td','/html/body/center/table/tbody/tr/td/table[2]/tbody/tr/td/table[3]/tbody/tr[2]/td/table[1]/tbody/tr[1]/td'],
                'pdate':['/html/body/table/tbody/tr/td/table[2]/tbody/tr[1]/td/table[1]/tbody/tr[2]/td/text()[1]','/html/body/center/table/tbody/tr/td/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td/table/tbody/tr[2]/td[1]'],
                'showcontent':['//*[@id="fontzoom"]'],
        },
        'www.jxsfdc.com': {
                'lang':'zh',
                'title':[''],
                'pdate':[''],
                'showcontent':[''],
        },
        'www.jxjst.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="page4"]/div/div[2]/div[1]/h1'],
                'pdate':['//*[@id="page4"]/div/div[2]/div[1]/table/tbody/tr[2]/td[4]'],
                'showcontent':['//*[@id="detailContent"]'],
        },
        'www.lnjst.gov.cn': {
                'lang':'zh',
                'title':['//div[@class="Articel_Title"]'],
                'pdate':['//div[@class="Articel_Date"]'],
                'showcontent':['//div[@class="Acontent"]','//*[@id="form1"]/div[7]/div[2]/div[3]'],
        },
        'www.imre.gov.cn': {
                'lang':'zh',
                'title':['/html/body/center/table[3]/tbody/tr[1]/td'],
                'pdate':['//*[@class="Articel_Date"]'],
                'showcontent':['/html/body/center/table[3]'],
        },
        'www.nmfgj-gov.cn': {
                'lang':'zh',
                'title':['//*[@id="container"]/div[2]/div/div[2]/h3'],
                'pdate':['//*[@id="container"]/div[2]/div/div[2]/div[1]/span'],
                'showcontent':['//*[@id="container"]/div[2]/div/div[2]/div[2]'],
        },
        'www.nxjst.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[1]/div[3]/div[3]/div[2]/form/div[1]'],
                'pdate':['/html/body/div[1]/div[3]/div[3]/div[2]/form/div[3]/text()[1]','//*[@class="info_title"]'],
                'showcontent':['//*[starts-with(@id,"vsb_content")]'],
        },
        'www.nxgtt.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="table1"]/tbody/tr/td/table/tbody/tr[1]/td'],
                'pdate':['//*[@id="table1"]/tbody/tr/td/table/tbody/tr[2]/td/span[1]'],
                'showcontent':['//*[@id="vsb_content"]'],
        },
        'www.qhlr.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[4]/p'],
                'pdate':['/html/body/div[4]/div[1]/span[2]"]'],
                'showcontent':['/html/body/div[4]/div[2]'],
        },
        'www.sddlr.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="gkml"]/div[1]/div[4]','//*[@id="article"]/div[1]/div[4]/div[1]','//*[@class="title"]'],
                'pdate':['//*[@id="article"]/div[1]/div[4]/div[5]/span[2]','//*[@id="gkml"]/div[1]/div[3]/div[1]/dl[4]/dd'],
                'showcontent':['//*[@id="ztdx"]'],
        },
        'www.shanxilr.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="main_ArticleTitle"]'],
                'pdate':['//*[@class="Article_tdbgall"]/td/text()[2]','//*[@class="Article_tdbgall"]'],
                'showcontent':['//*[@id="fontzoom"]'],
        },
        'www.shaanxijs.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[2]/div[2]/h1', '//*[@class="newsTitle"]', '//h1' ],
                'pdate':['/html/body/div[2]/div[2]/div[1]/span[2]', '//*[@id="form1"]/table/tbody/tr/td/table[3]/tbody/tr/td[3]/table/tbody/tr/td/table/tbody/tr[2]/td/table[2]/tbody/tr[3]/td/table/tbody/tr/td[2]'],
                'showcontent':['/html/body/div[2]/div[2]/div[2]', '//*[@id="jscontent"]'],
        },
        'www.scdlr.gov.cn': {
                'lang':'zh',
                'title':['//div[@class="Title"]/div'],
                'pdate':['//div[@class="Attribute"]'],
                'showcontent':['//div[@class="ConText"]'],
        },
        'www.xzcs.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div/div[2]/div[1]/div[2]/p[1]','//*[@class="x-main-qydj-title"]'],
                'pdate':['/html/body/div/div[2]/div[1]/div[2]/p[2]','//*[@class="x-main-qydj-date"]'],
                'showcontent':['/html/body/div/div[2]/div[1]/div[3]','//*[@class="x-main-qydj-body"]'],
        },
        'www.xzgtt.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="fontbiaoti"]'],
                'pdate':['/html/body/table[5]/tbody/tr/td[2]/table[2]/tbody/tr[2]/td/table/tbody/tr[3]/td/font'],
                'showcontent':['//*[@id="contentinfo"]/div'],
        },
        'www.xjjs.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div/div[5]/div[1]/div[2]/div/div[1]/h2'],
                'pdate':['/html/body/div/div[5]/div[1]/div[2]/div/div[2]'],
                'showcontent':['/html/body/div/div[5]/div[1]/div[2]/div/div[3]'],
        },
        'www.xjgtzy.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="13495"]/table[1]/tbody/tr/td/table[1]/tbody/tr[2]/td'],
                'pdate':['//*[@id="13495"]/table[1]/tbody/tr/td/table[2]/tbody/tr/td'],
                'showcontent':['//*[@id="13495"]/table[1]/tbody/tr/td/table[3]/tbody/tr/td'],
        },
        'www.ynhouse.org': {
                'lang':'zh',
                'title':['//*[@id="LbTitle"]','/html/body/table[3]/tbody/tr/td[2]/table/tbody/tr/td/table[2]/tbody/tr[1]/td/div/table[1]/tbody/tr[1]/td[2]'],
                'pdate':['//*[@id="LbTime"]','/html/body/table[3]/tbody/tr/td[2]/table/tbody/tr/td/table[2]/tbody/tr[1]/td/div/table[1]/tbody/tr[3]/td[2]'],
                'showcontent':['/html/body/table[3]/tbody/tr/td[2]/table/tbody/tr/td/table[2]/tbody/tr[1]/td/div/table[2]/tbody','/html/body/table[3]/tbody/tr/td[2]/table/tbody/tr/td/table[2]/tbody/tr[1]/td/div/table[2]/tbody/tr/td'],
        },
        'www.ynfgj.com.cn': {
                'lang':'zh',
                'title':['//*[@class="Article_right_ContentDown_Title"]'],
                'pdate':['//*[@class="Article_right_ContentDown_Instructions"]'],
                'showcontent':['//*[@class="rightcontent_content"]'],
        },
        'www.yndlr.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="ArticleTitle"]', '//*[@class="title"]', '//*[@id="lbTopic"]','//h1'],
                'pdate':['//*[@class="ArticleAbout"]', '//*[@class="time"]','//*[@id="lbPostTime"]'],
                'showcontent':['//*[@class="ArticleBody"]', '//*[@class="text"]', '//*[@class="content"]'],
        },
        'www.zjdlr.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="c"]/tbody/tr[1]/td','//*[@class="title"]'],
                'pdate':['//*[@id="c"]/tbody/tr[4]/td/table/tbody/tr/td[2]','//*[@id="article"]/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/span'],
                'showcontent':['//*[@id="zoom"]'],
        },      
        'www.mlr.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="doctitle"]/tbody/tr[1]/td','//*[@id="content"]/div[1]//font','//*[@class="zw_title"]','//*[@id="content"]/p[2]'],
                'pdate':['//*[@id="map"]/tbody/tr/td/table/tbody/tr/td[2]/table[6]/tbody/tr[2]/td','//*[@id="country"]/div[2]/div[4]/span[1]'],
                'showcontent':['//*[@id="content1"]','//*[@id="content"]'],
        },      
        'www.mohurd.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="tit"]'],
                'pdate':['//div[@class="union"]//p[@style="text-align: right"]'],
                'showcontent':['//div[@class="union"]'],
        },
        'www.ndrc.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="out-content"]/div[2]/div[2]/div/div[2]'],
                'pdate':['//*[@id="out-content"]/div[2]/div[2]/div/div[3]]'],
                'showcontent':['//*[@id="zoom"]/div'],
        },      

        'www.bjjs.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="container"]/table/tbody/tr[1]/td/h1'],
                'pdate':['//*[@id="container"]/table/tbody/tr[2]/td/span[2]'],
                'showcontent':['//*[@id="Zoom"]/div'],
        },      
        'www.qhcin.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="titlestyle1099"]'],
                'pdate':['//*[@class="timestyle1099"]'],
                'showcontent':['//*[starts-with(@id,"vsb_content")]'],
        },      
        'www.gzjs.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="title"]','//*[@class="lqlst3"]'],
                'pdate':['//*[@class="toolbar"]/p/text()[3]','//*[@id="line"]/table/tbody/tr/td[2]'],
                'showcontent':['//*[@class="content"]','//*[@//*[@id="jscontent"]]'],
        },      
        'jsjtw.sh.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="ivs_title"]'],
                'pdate':['//*[@id="main"]/div[2]/div/div[2]/span'],
                'showcontent':['//*[@id="ivs_content"]'],
        },
        'www.gov.cn': {
                'lang':'zh',
                'title':['/html/body/div[2]/div[1]/div[2]/h1','//h1'],
                'pdate':['//*[@class="pages-date"]'],
                'showcontent':['//*[@class="pages_content"]'],
        },
        'www.mofcom.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="artitle"]'],
                'pdate':['//*[@id="arsource"]/text()[2]'],
                'showcontent':['//*[@id="zoom"]'],
        },
        'www.mof.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="font_biao1"]','//h3'],
                'pdate':['/html/body/table/tbody/tr[2]/td/table/tbody/tr[2]/td/table[3]/tbody/tr/td/center/p[1]','//*[@id="middle"]/table/tbody/tr[2]/td[1]/div/div[2]'],
                'showcontent':['//*[@id="zoom"]','//*[@class="TRS_Editor"]'],
        },
        'www.sdpc.gov.cn': {
                'lang':'zh',
                #'title':['//*[@id="ivs_title"]'],
                'pdate':['//*[@id="out-content"]/div[2]/div[2]/div/div[3]'],
                'showcontent':['//*[@class="TRS_Editor"]'],
        },
        'www.fmprc.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="News_Body_Title"]'],
                'pdate':['//*[@id="News_Body_Time"]'],
                'showcontent':['//*[@id="News_Body_Txt_A"]'],
        },
        'www.mca.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="artmain"]/div[2]/h3','/html/body/table/tbody/tr/td[2]/table[1]/tbody/tr/td/table/tbody/tr[3]/td[2]'],
                'pdate':['//*[@id="artmain"]/div[2]/div[1]/center/text()[3]','/html/body/table/tbody/tr/td[2]/table[1]/tbody/tr/td/table/tbody/tr[3]/td[2]'],
                'showcontent':['//*[@id="zoom"]','/html/body/table/tbody/tr/td[2]/table[1]/tbody/tr/td/table/tbody/tr[3]/td[2]'],
        },
        'www.gddrc.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="xlbox"]/h4'],
                'pdate':['//*[@class="xlbox"]/h6'],
                'showcontent':['//*[@class="TRS_Editor"]'],
        },
        'www.gddoftec.gov.cn': {
                'lang':'zh',
                'title':['//*[@class="tit05"]'],
                'pdate':['//*[@class="td01"]'],
                'showcontent':['//*[@class="TRS_Editor"]'],
        },
        'www.safe.gov.cn': {
                'lang':'zh',
                'title':['//*[@id="Title"]'],
                'pdate':['//*[@class="headInfo"]'],
                'showcontent':['//*[@id="newsContent"]'],
        },
        'www.infrastructure.gov.au': {
                'lang':'en',
                'title':['//article//h1','//h1'],
                'pdate':['//*[@id="text"]/div/div[1]/p[3]'],
                'showcontent':['//*[@id="text"]'],
        },
        'www.dfat.gov.au': {
                'lang':'en',
                'title':['//header/h1/text()'],
                'pdate':['//*[@id="text"]/div/div[1]/p[3]/text()'],
                'showcontent':['//div[@class="contentarea"]','//div[starts-with(@id,"WebPartZone")]/div/*'],
                'category':['//header/p/a/text()'],
        },
        'www.gov.uk': {
                'lang':'en',
                'title':['//header/h1/text()','//h1'],
                'pdate':['//*[@class="published definition"]','//div[@class="govuk-metadata direction-ltr"]/dl'],
                'showcontent':['//*[@id="content"]/p','//*[@id="govspeak"]'],
        },
        'www.nsw.gov.au': {
                'lang':'en', 
                'title':['//p[starts-with(@class,"heading-3")]','//*[@id="contentArea"]/h1','//h1'],
                'pdate':['//div[@class="article-content__bottom-section-content"]/div/span[1]','//*[@id="datestamp"]/p'],
                'showcontent':['//*[@class="element ElementContent"]/div/*','//*[@id="contentArea"]'],
        },
        'www.birmingham.gov.uk': { 
                'lang':'en',
                'title':['//*[@id="content"]/h1'],
                'pdate':['//*[@id="content"]/div[1]/span'],
                'showcontent':['//*[@id="content"]/p', '//*[@id="content"]/div[2]'],
        },
        'www.londoncouncils.gov.uk': {
                'lang':'en',
                'title':['//h1[@class="page_header"]'],
                'pdate':['//*[@id="content"]/div[1]/span'],
                'showcontent':['//*[@id="content"]/p', '//*[@id="content"]/div[2]'],
        },
        'www.treasury.gov.my': {
                'lang':'en',
                'title':['//h2[@class="itemTitle"]'],
                'pdate':['//span[@class="itemDateCreated"]'],
                'showcontent':['//div[@class="itemFullText"]'],
        },
        'www.customs.gov.my': {
                'lang':'en',
                'title':['//*[@id="ctl00_PlaceHolderMain_grdAnnoucementList"]/tbody/tr/td/h4/text()'],
                'pdate':['//*[@id="ctl00_PlaceHolderMain_grdAnnoucementList"]/tbody/tr/td/p[1]'],
                'showcontent':['//*[@id="ctl00_PlaceHolderMain_grdAnnoucementList"]/tbody/tr/td/div'],
        },
        'www.miti.gov.my': {
                'lang':'en',
                'title':['//*[@class="page-title"]/h1'],
                'pdate':['//*[@id="container_content"]/div[3]/p'],
                'showcontent':['//*[@id="container_content"]'],
        },
        'www.kpkt.gov.my': {
        },
	'www.bpn.go.id': {
                'lang':'en',
                'title':['//*[@class="article-details"]/h1','//h1'],
                'pdate':['//*[@class="date-no-image"]/p','//*[starts-with(@class,"date")]/p','//*[@class="newstwo-date"]'],
                'showcontent':['//*[@class="EDN_article_content"]'],
        },        
	'ekon.go.id': {
                'lang':'yinni',
                'title':['//*[@class="boxtitle_home"]'],
                'pdate':['//*[@class="boxnews_home"]//b/text()','//*[@id="m_main"]/table/tbody/tr/td[2]/div/div[1]/table/tbody/tr/td[2]/b/text()'],
                'showcontent':['//*[@class="boxnews_home"]/div[3]','//*[@class="boxnews_home"]//p'],
        },
	'www.vic.gov.au': {
                'lang':'en',
                'title':['//h1'],
                'pdate':['//*[@class="date"]'],
                'showcontent':['//*[@class="g8"]//p','//*[@class="latest-block"]//p'],
        },
	'www.gov.hk': {
                'lang':'zh',
                'title':['//*[@id="PRHeadlineSpan"]','//*[@id="newsTitle"]'],
                'pdate':['//*[@id="pressrelease"]/div[3]','//*[@id="date"]'],
                'showcontent':['//*[@id="content1"]'],
        },
	'www.kemenkeu.go.id': {
                'lang':'en',
                'title':['//*[@id="breadcrumbs-inner"]/div/a[2]','//*[starts-with(@id,"node-")]/div[2]/div[3]/div/div'],
                'pdate':['//*[@class="submitted"]'],
                'showcontent':['//*[@class="rtejustify"]'],
        },
	'www.mida.gov.my': {
                'lang':'en',
                'title':['//h1'],
                'pdate':['//*[@id="MainInfo"]/article/div/strong/small'],
                'showcontent':['//*[@id="MainInfo"]/article','//*[@id="MainInfo"]'],
        },
	'www.pbc.gov.cn': {
                'lang':'zh',
                'title':['//h2'],
                'pdate':['//*[@id="10929"]/div[2]/table[2]/tbody/tr/td/table/tbody/tr/td/table[2]/tbody/tr/td[4]'],
                'showcontent':['//*[@id="MainInfo"]/article','//*[@id="MainInfo"]'],
        },
}
